on:
  pull_request:
    branches:
      - master

name: Test Across Matrix

jobs:
  test:
    # env:
    #   REPO_PATH: ${{ github.workspace }}
    ## We want to define a strategy for our job
    strategy:
      ## this will contain a matrix of all of the combinations
      ## we wish to test again:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    
    ## Defines the platform for each test run
    runs-on: ${{ matrix.platform }}
    
    ## the steps that will be run through for each version and platform
    ## combination
    steps:
    ## sets up go based on the version
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
    ## checks out our code locally so we can work with the files
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          path: go/src/go.starlark.net
    
    - name: Install dependencies
      run: go mod download

    ## runs go test ./...
    - name: Test
      run: |
        echo $(pwd)
        echo ${GOPATH}
        echo ${GOROOT}
        go test -race -vet all -mod readonly ./...